<?php

namespace IPSM\IpManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpRepository extends EntityRepository
{
}
