<?php

namespace IPSM\IpManagerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaRepository extends EntityRepository
{
    public function getQueryPersona(Persona $persona)
    {
        $q = $this->createQueryBuilder("p")
            ->andWhere("p.persona = :persona")
            ->addOrderBy("p.id")
            ->addOrderBy("p.nombre")
            ->addOrderBy("p.correo")
            ->setParameter("persona", $persona->getId());
        return $q;
    }
}
